---

# Automatically build, validate, and deploy the devbox project

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --show-version"


# Build the docker images
build:
  stage: build
  image: maven:3.5.3-jdk-8
  script:
    - cd ${CI_PROJECT_DIR}
    - make build

# Test the docker images
test:
  stage: test
  image: maven:3.5.3-jdk-8
  script:
    - cd ${CI_PROJECT_DIR}
    - make test

deploy:
  stage: deploy
  image: maven:3.5.3-jdk-8
  only:
    - master
    - tags
  script:
    - cd ${CI_PROJECT_DIR}
    - make build
    - make push-version
