version: "2"

services:
  namenode:
    image: dtspence/hadoop-namenode:compose-2.6.0-cdh5.9.1
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
  
  resourcemanager:
    image: dtspence/hadoop-resourcemanager:compose-2.6.0-cdh5.9.1
    container_name: resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode1:50075 datanode2:50075"
    env_file:
      - ./hadoop.env

  historyserver:
    image: dtspence/hadoop-historyserver:compose-2.6.0-cdh5.9.1
    container_name: historyserver
    ports:
      - "19888"
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode1:50075 resourcemanager:8088"
    env_file:
      - ./hadoop.env
  
  nodemanager1:
    image: dtspence/hadoop-nodemanager:compose-2.6.0-cdh5.9.1
    container_name: nodemanager1
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode1:50075 resourcemanager:8088"
    env_file:
      - ./hadoop.env
  
  datanode1:
    image: dtspence/hadoop-datanode:compose-2.6.0-cdh5.9.1
    container_name: datanode1
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
  
  datanode2:
    image: dtspence/hadoop-datanode:compose-2.6.0-cdh5.9.1
    container_name: datanode2
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

  datanode3:
    image: dtspence/hadoop-datanode:compose-2.6.0-cdh5.9.1
    container_name: datanode3
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_datanode3:
